Updated README and created OperatorWebSite class

diff --git a/bin/web_crawler b/bin/web_crawler
--- a/bin/web_crawler
+++ b/bin/web_crawler
@@ -1,30 +1,14 @@
 #!/bin/bash
 
-# CHECK BASH VERSION FOR ASSOCIATIVE ARRAY
-# /usr/local/bin/bash new
-# /bin/bash old
-
-# This bash script wraps the functionalities
-
-exit_codes=
-
-if [[ "$BASH_VERSION" =~ ^4 ]]
-then
-    echo "OLD!!!!!!!!!!!!!!"
-    exit
-
-    # Exit codes
-    declare -A exit_codes
-    exit_codes=([SUCCESS]=0 [FAIL]=1)
-else
-    exit_codes=1
-fi
-
-
+# This bash script wraps the functionalities of web_crawler.py
 
 me=$(basename $0)
 binpath=$(dirname $0)
 script=project/web_crawler.py
+
+# Exit codes
+OK=0
+FAIL=1
 
 # Usage functions
 function synopsis {
@@ -39,6 +23,8 @@ function get_options {
     export pattern_one=$pos_args
     export pattern_two=$opt_args
 	usage_txt=$(python $script --help)
+
+    # Get positional arguments
     script="$(cat <<"EOF"
     # Get each option
     if ((/$ENV{pattern_one}/../$ENV{pattern_two}/) &&    # Print anything between
@@ -66,30 +52,54 @@ function get_options {
     }
 EOF
 )"
-
-    # Get positional arguments
 	echo "$usage_txt" | perl -ne "$script"
+
     # Get optional arguments
     script="$(cat <<"EOF"
-    my $pad = " " x 5;
+    my $pad = " " x 4;
+
     if ($can_print) {
+        my $opt = $_;
+        # Remove traling or leading spaces
+        $opt =~ s/^[\s\t]+|[\s\t]+$//g;
+        # Multiline comment
         if ($_ =~ /^\s+[a-zA-Z]+/) {
             if ($_ !~ /^\s+$/) {
-                print($pad . $pad . " " x 3 . $_);
+                if ($no_pad eq 1) {
+                    if ($prev) {
+                        printf("\n${prev}\t\t%s\n", $opt);
+                        $prev = "";
+                    }
+                    $no_pad = 0;
+                }
+                else {
+                    printf("%s$opt\n", $pad x 8);
+                }
             }
             next;
         }
         else {
-            my $opt = $_;
-            # Remove traling or leading spaces
-            $opt =~ s/^\s+|\s+$//g;
-            # Add double hypen for positional arguments
-            $opt =~ s/^[^-](.+)$/--$1/;
-            $opt =~ s/^(.+)$/${pad}${1}\n/;
+
             # Readjust the spacing
             $opt =~ s/(.+)(\s{2,})/$1\t\t/;
-            if ($opt !~ /^\s+$/) {
-                print("\n$opt");
+
+            # Add padding
+            $opt =~ s/^(.+)$/${pad}${1}/;
+
+            $no_pad = 0;
+
+            if ($opt =~ /\t[\w\d]+/) {
+                # Add newline
+                if ($opt !~ /\n$/) {
+                    $opt =~ s/^(.+)$/$1\n/;
+                }
+                if ($opt !~ /^\s+$/) {
+                    print("\n$opt");
+                }
+            }
+            else {
+                $no_pad = 1;
+                $prev = $opt;
             }
         }
     }
@@ -102,86 +112,119 @@ EOF
 }
 
 function get_version {
-    echo $(python $script --version 2>&1)
+    version="$(python $script --version 2>&1)"
+    echo ${version/.py/}
 }
 
 function usage {
     bold=$(tput bold)
     underline=$(tput smul)
     reset=$(tput sgr0)
+    # redirect usage >&2
 	cat <<-END
 ${bold}NAME${reset}
-     ${me} -- calling costs web crawler
+
+    ${me} -- networks' international calling costs web crawler
 
 ${bold}SYNOPSIS${reset}
-     $(synopsis)
-     (See the OPTIONS section for alternate option syntax with long option names.)
+
+    $(synopsis)
+
+    (See the OPTIONS section for alternate option syntax with long option names.)
 
 ${bold}DESCRIPTION${reset}
-     ${underline}${me}${reset} is a simple web crawler for networks’ international calling costs.
 
-     The script queries a network’s website directly to obtain a list of calling costs.
-     These costs are: based on country zones, per minute and only related to calls to
-     a foreign country from the UK.
+    ${underline}${me}${reset} is a simple web crawler for networks’ international calling costs.
 
-     ${underline}${me}${reset} requires a JSON file containing:
-         - the operator URL
-         - the list of country zones
-         - the file structure for the Selenium driver
+    The script queries a network’s website directly to obtain a list of calling costs.
+    These costs are: based on country zones, per minute and only related to calls to
+    a foreign country from the UK.
 
-     A log file can be used to track the crawling process, if not supplied then all the
-     messages will be printed to STDOUT (default).
+    ${underline}${me}${reset} requires a JSON file containing:
+        - operator name
+        - operator URL
+        - list of country zones
+        - list of actions for the Selenium driver
+        - load time: the maximum amount of time to wait for a page element to get loaded
+        - sleep time: the amount of time of sleeping after each action
+
+    A log file can be used to track the crawling process, if not supplied then all the
+    messages will be printed to STDOUT (default).
 
 ${bold}OPTIONS${reset}
-     $(get_options)
+
+    $(get_options)
 
 ${bold}EXAMPLES${reset}
-     TODO: Show some examples of how to use this script.
+
+    Run with logging at debug level, printing to STDOUT:
+
+        web_crawler --data ../data/sites/operators.json -l "debug"
+
+    Print the output to STDOUT in JSON format:
+
+        web_crawler --data ../data/sites/operators.json --json
+
+    Print the output to a file in JSON format:
+
+        web_crawler --data ../data/sites/operators.json --json --out file.json
+
+    Log the process to a specific directory:
+
+        web_crawler --data ../data/sites/operators.json --lod-dir /var/log/
+
 
 ${bold}REQUIREMENTS${reset}
-     Python modules: argparse, coloredlog, chromedriver, selenium
+
+    Python modules: argparse, coloredlog, chromedriver, selenium
 
 ${bold}EXIT CODES${reset}
-     0 - Success
-     1 - Failure
+
+    0 - Success
+    1 - Failure
 
 ${bold}AUTHOR${reset}
-     Luigi Riefolo <luigi.riefolo@gmail.com>
+
+    Luigi Riefolo <luigi.riefolo@gmail.com>
 
 ${bold}LICENSE${reset}
-     This script is in the public domain, free from copyrights or restrictions.
+
+    This script is in the public domain, free from copyrights or restrictions.
 
 ${bold}VERSION${reset}
-     $(get_version)
+
+    $(get_version)
 
 END
 }
 
 
 # Script invoked with no command-line args
+
 if [[ $# == 0 ]]
 then
 	usage
 	exit $E_OPTERROR
 fi
 
-while getopts ":h" opt
-do
-	case $opt in
-		h)
-      		usage
-      		exit 1
-      		;;
-		:)
-      		echo "Option -$OPTARG requires an argument." >&2
-      		exit 1
-      		;;
-    	\?)
-      		echo "Invalid option: -$OPTARG" >&2
-			exit FAIL
-      		;;
-  	esac
+optspec=":hv-:"
+while getopts "$optspec" optchar; do
+    case "${optchar}" in
+        h)
+            usage
+            exit $OK
+            ;;
+        *)
+            if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
+                echo "Non-option argument: '-${OPTARG}'" >&2
+            fi
+            ;;
+    esac
 done
 
-
 python "$binpath/../$script" $@
+ret=$?
+if [[ $ret -ne 0 ]];
+then
+    echo "See the usage: web_crawler -h"
+fi
